[project]
authors = ["hlm628 <henry@hlm628.com>"]
channels = ["conda-forge"]
name = "hackanoho-2025"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = "4.*"
pandas = ">=2.2.3,<3"
numpy = ">=2.0.2,<3"
matplotlib = ">=3.9.4,<4"
